services:
  postgres:
    ports:
      - "${ARKLOOP_POSTGRES_PORT:-5432}:5432"

  redis:
    ports:
      - "${ARKLOOP_REDIS_PORT:-6379}:6379"

  api:
    ports:
      - "${ARKLOOP_API_PORT:-8001}:8001"

  pgbouncer:
    ports:
      - "${ARKLOOP_PGBOUNCER_PORT:-5433}:5432"

  browser:
    ports:
      - "${ARKLOOP_BROWSER_PORT:-3100}:3000"

  sandbox:
    ports:
      - "${ARKLOOP_SANDBOX_PORT:-8002}:8002"

  sandbox-docker:
    ports:
      - "${ARKLOOP_SANDBOX_PORT:-8002}:8002"

  openviking:
    ports:
      - "${ARKLOOP_OPENVIKING_PORT:-1933}:1933"
