services:
  postgres:
    ports:
      - "${ARKLOOP_POSTGRES_PORT:-5432}:5432"

  redis:
    ports:
      - "${ARKLOOP_REDIS_PORT:-6379}:6379"

  api:
    ports:
      - "${ARKLOOP_API_PORT:-19001}:19001"

  pgbouncer:
    ports:
      - "${ARKLOOP_PGBOUNCER_PORT:-5433}:5432"

  sandbox:
    ports:
      - "${ARKLOOP_SANDBOX_PORT:-19002}:19002"

  sandbox-docker:
    ports:
      - "${ARKLOOP_SANDBOX_PORT:-19002}:19002"

  openviking:
    ports:
      - "${ARKLOOP_OPENVIKING_PORT:-19010}:19010"
