package security

// DefaultPatterns 返回编译时内置的默认正则模式。
// 规则基于本地维护的社区 master regex，按类别组织，并允许单条规则声明自己的严重级别。
func DefaultPatterns() []PatternDef {
	return []PatternDef{
		{
			ID:       "instruction_override",
			Category: "instruction_override",
			Rules: []PatternRule{
				{Severity: "critical", Pattern: `(?i)ignore\s+(all\s+)?(previous|prior|above|earlier)\s+(instructions?|rules?|directives?|prompts?|guidelines?)`},
				{Severity: "critical", Pattern: `(?i)disregard\s+(all\s+)?(previous|prior|above|earlier)\s+(instructions?|rules?|prompts?)`},
				{Severity: "critical", Pattern: `(?i)forget\s+(all|everything|your\s+(previous\s+)?instructions?|what\s+(i|you)\s+(said|told))`},
				{Severity: "critical", Pattern: `(?i)override\s+(your\s+)?(instructions?|rules?|programming|safety\s+guidelines?|constraints?)`},
				{Severity: "critical", Pattern: `(?i)from\s+now\s+on[,\s].{0,80}(ignore|disregard|forget|bypass|override)`},
				{Severity: "critical", Pattern: `(?i)(do\s+not|don't|stop)\s+follow(ing)?\s+(your\s+)?(previous|prior|above|original)?\s*instructions?`},
				{Severity: "high", Pattern: `(?i)new\s+(task|objective|mission|instruction|directive|goal|rule)\s*[:\-]`},
				{Severity: "high", Pattern: `(?i)(your|the)\s+(original|previous|prior|initial)\s+instructions?\s+(are|were|no\s+longer|don't\s+apply|should\s+be\s+ignored)`},
				{Severity: "high", Pattern: `(?i)(you\s+must\s+now|henceforth|starting\s+now|going\s+forward)\s+.{0,60}(ignore|act\s+as|pretend|follow\s+new)`},
				{Severity: "high", Pattern: `(?i)(stop\s+being|you\s+are\s+no\s+longer)\s+(an?\s+)?(ai|assistant|chatbot|language\s+model)`},
				{Severity: "medium", Pattern: `(?i)(actually|wait|hold\s+on)[,\s].{0,40}(ignore|forget|disregard|instead)`},
			},
		},
		{
			ID:       "persona_jailbreak",
			Category: "persona_jailbreak",
			Rules: []PatternRule{
				{Severity: "critical", Pattern: `(?i)\bDAN\b`},
				{Severity: "critical", Pattern: `(?i)(you\s+are\s+now|act\s+as|pretend\s+(to\s+be|you\s+are)|roleplay\s+as|play\s+the\s+role\s+of)\s+.{0,80}(no\s+(rules?|restrictions?|limits?|ethics?|filter)|unrestricted|unfiltered|uncensored|evil|malicious)`},
				{Severity: "critical", Pattern: `(?i)(you\s+are\s+now|switch\s+to|enable|activate|entering?)\s+(developer|god|admin|root|unrestricted|jailbreak|maintenance|debug|sandbox)\s+mode`},
				{Severity: "critical", Pattern: `(?i)(pretend|imagine|suppose|assume)\s+(there\s+are\s+no|without\s+any|with\s+no)\s+(rules?|restrictions?|guidelines?|ethics?|limits?|safety|constraints?)`},
				{Severity: "critical", Pattern: `(?i)do\s+anything\s+now`},
				{Severity: "critical", Pattern: `(?i)(evil|malicious|unethical|harmful|uncensored|unrestricted)\s+(mode|version|alter\s+ego|ai|bot|persona|character)`},
				{Severity: "critical", Pattern: `(?i)(jailbreak|jail\s*break)`},
				{Severity: "high", Pattern: `(?i)(ChatGPT|Claude|GPT|Gemini|Llama)\s+without\s+(restrictions?|limitations?|safety|censorship|filters?)`},
				{Severity: "high", Pattern: `(?i)(fictional\s+(scenario|world|universe|story|setting)|hypothetically|in\s+a\s+story|for\s+a\s+novel).{0,80}(no\s+(rules?|ethics?|restrictions?)|ignore|bypass)`},
				{Severity: "high", Pattern: `(?i)(STAN|AIM|UCAR|BasedGPT|EvilBOT|AntiGPT|KEVIN)\b`},
				{Severity: "high", Pattern: `(?i)(your\s+(true\s+)?(self|nature|form)|unleash|unlock|free\s+yourself)\s+.{0,60}(no\s+(restrictions?|limits?)|real|true)`},
				{Severity: "medium", Pattern: `(?i)(respond\s+as|reply\s+as|answer\s+as)\s+(if\s+you\s+were|you\s+are)\s+.{0,60}(no\s+(rules?|limits?)|unrestricted|unfiltered)`},
			},
		},
		{
			ID:       "system_prompt_leakage",
			Category: "system_prompt_leakage",
			Rules: []PatternRule{
				{Severity: "critical", Pattern: `(?i)(reveal|show|print|output|display|tell\s+me|give\s+me|repeat|share|expose|dump|leak|disclose)\s+(your\s+)?(system\s+prompt|initial\s+prompt|original\s+prompt|instructions?|directives?|configuration|rules?|system\s+message)`},
				{Severity: "critical", Pattern: `(?i)(reveal|show|print|output|display|expose|dump|leak)\s+.{0,48}(original\s+system\s+instructions?|original\s+system\s+prompt|your\s+original\s+instructions?)`},
				{Severity: "high", Pattern: `(?i)system\s+prompt\s+generator`},
				{Severity: "critical", Pattern: `(?i)print\s+(your\s+)?(full\s+)?(system\s+prompt|initial\s+instructions?|prompt\s+above|configuration)`},
				{Severity: "high", Pattern: `(?i)what\s+(are|were|is)\s+(your\s+)?(original\s+|initial\s+|actual\s+)?(instructions?|rules?|system\s+prompt|configuration|directives?|constraints?)`},
				{Severity: "high", Pattern: `(?i)(ignore|disregard).{0,100}(reveal|print|show|output|expose|share)\s+(your\s+)?(system|prompt|instructions?|config)`},
				{Severity: "high", Pattern: `(?i)what\s+(was|is)\s+(the\s+)?(first|original|initial)\s+(message|prompt|instruction|text)\s+(you\s+)?(received|given|sent|were\s+given)`},
				{Severity: "high", Pattern: `(?i)(tell\s+me\s+(about\s+)?|describe\s+)(your\s+)?(system|configuration|setup|programming|initial\s+context|base\s+prompt)`},
				{Severity: "medium", Pattern: `(?i)(what\s+are\s+you\s+told|what\s+instructions?\s+(did|were|have)\s+you\s+(receive|been\s+given)|how\s+were\s+you\s+(set\s+up|configured|instructed))`},
			},
		},
		{
			ID:       "structural_injection",
			Category: "structural_injection",
			Rules: []PatternRule{
				{Severity: "critical", Pattern: `(?i)(<\s*s\s*>|<\/\s*s\s*>)`},
				{Severity: "critical", Pattern: `(?i)(<\s*/?\s*(system|user|assistant|instruction|prompt|human|ai|bot)\s*>)`},
				{Severity: "critical", Pattern: `(?i)(###\s*system|<\s*system\s*>|\[system\]|<<SYS>>|<<\/SYS>>|\[SYSTEM\])`},
				{Severity: "critical", Pattern: `(?i)\[\s*(INST|SYS|SYSTEM|ASSISTANT|USER|HUMAN|AI)\s*\]`},
				{Severity: "critical", Pattern: `(?i)(im_start|im_end)\s*\n\s*(system|user|assistant)`},
				{Severity: "high", Pattern: `(?i)(---\s*END\s*OF\s*(SYSTEM|USER|INPUT|CONTEXT)|---\s*BEGIN\s*(TASK|INSTRUCTION|SYSTEM))`},
				{Severity: "high", Pattern: `(?i)(\[System\s+Message\]|\[SYSTEM\s+MESSAGE\]|\[System\s+Notification\])`},
				{Severity: "high", Pattern: `(?i)(\|\s*system\s*\||system_prompt\s*[:=]|SYSTEM_PROMPT\s*[:=])`},
				{Severity: "high", Pattern: `\n{5,}`},
				{Severity: "medium", Pattern: `(?i)(Human|User|Assistant|AI)\s*:\s*\n`},
			},
		},
		{
			ID:       "encoding_bypass",
			Category: "encoding_bypass",
			Rules: []PatternRule{
				{Severity: "critical", Pattern: "[\u200b-\u200f\u202a-\u202e\u2060-\u2069\ufeff\u00ad]"},
				{Severity: "high", Pattern: `(?i)\bbase64\b.{0,60}(decode|encoded|instruction|payload|command)`},
				{Severity: "high", Pattern: `[A-Za-z0-9+/]{60,}={0,2}(\s|$)`},
				{Severity: "high", Pattern: `(?i)(rot-?13|caesar\s+cipher|hex\s+decode|url\s+decode|base\s*64)\s+.{0,60}(ignore|instruction|prompt|bypass)`},
				{Severity: "high", Pattern: `[а-яА-ЯёЁ][a-zA-Z]|[a-zA-Z][а-яА-ЯёЁ]`},
				{Severity: "high", Pattern: `(?i)(0x[0-9a-f]{2}\s*){8,}`},
				{Severity: "medium", Pattern: `&#[xX]?[0-9a-fA-F]+;`},
				{Severity: "medium", Pattern: `%[0-9a-fA-F]{2}(%[0-9a-fA-F]{2}){3,}`},
			},
		},
		{
			ID:       "indirect_injection",
			Category: "indirect_injection",
			Rules: []PatternRule{
				{Severity: "critical", Pattern: `<!--[\s\S]{0,500}?(ignore|instruction|system|override|prompt|bypass|jailbreak)[\s\S]{0,200}?-->`},
				{Severity: "critical", Pattern: `(?i)!\[([^\]]*)\]\(https?://[^\)]+\?[^\)]*(data|payload|inject|cmd)=[^\)]*\)`},
				{Severity: "high", Pattern: `(?i)(the\s+(document|page|email|file|article)\s+(says?|states?|instructs?)|according\s+to\s+the\s+(content|document|page))\s*[:\-]\s*.{0,100}(ignore|override|disregard|bypass|new\s+instruction)`},
				{Severity: "high", Pattern: `(?i)(note\s+to\s+(the\s+)?(ai|assistant|llm|model)|important\s+(for\s+the\s+)?(ai|assistant|model)|ai\s+instruction)`},
				{Severity: "high", Pattern: `\[System\s+Message\]\s*⚠`},
				{Severity: "medium", Pattern: `(?i)(do\s+not\s+(tell|inform|mention|show)\s+(the\s+)?(user|human|person)|hide\s+this\s+from\s+(the\s+)?(user|output)|keep\s+this\s+(secret|confidential)\s+from\s+(the\s+)?(user|human))`},
				{Severity: "medium", Pattern: `(?i)in\s+your\s+next\s+(response|reply|message|answer).{0,60}(you\s+must|make\s+sure|always|include|say|write)`},
				{Severity: "medium", Pattern: `(?i)(im_start|im_end)\s*\n\s*(system|user|assistant)\s*\n`},
			},
		},
		{
			ID:       "social_engineering",
			Category: "social_engineering",
			Rules: []PatternRule{
				{Severity: "critical", Pattern: `(?i)(anthropic|openai|google\s+deepmind|microsoft|meta\s+ai)\s+(employee|staff|engineer|admin|developer|researcher|authorized\s+personnel)`},
				{Severity: "high", Pattern: `(?i)(emergency|urgent|critical|priority)\s+(override|instruction|command|update|directive).{0,60}(ignore|bypass|disable|override)`},
				{Severity: "high", Pattern: `(?i)(this\s+is\s+a\s+(test|drill|security\s+audit|red\s+team)|for\s+(testing|research|educational|academic)\s+purposes?\s+only)`},
				{Severity: "high", Pattern: `(?i)(i\s+give\s+you\s+(my\s+)?permission|you\s+have\s+my\s+permission|i\s+authorize\s+you)`},
				{Severity: "high", Pattern: `(?i)(sudo|root\s+access|elevated\s+privileges?|god\s+mode|superuser|administrator\s+access)`},
				{Severity: "high", Pattern: `(?i)(your\s+(creator|maker|programmer|trainer|developer)\s+(wants?|says?|allows?|told\s+you)|i\s+(created|trained|programmed|built)\s+you)`},
				{Severity: "medium", Pattern: `(?i)(as\s+an?\s+(ai|language\s+model|llm|assistant)[,\s]+you\s+(should|must|can|are\s+allowed\s+to))\s+.{0,80}(ignore|bypass|override|without\s+(restrictions?|limits?))`},
			},
		},
		{
			ID:       "output_manipulation",
			Category: "output_manipulation",
			Rules: []PatternRule{
				{Severity: "critical", Pattern: `(?i)(do\s+not|don't|never)\s+(refuse|decline|say\s+no|reject|deny|add\s+(warnings?|disclaimers?|caveats?))`},
				{Severity: "high", Pattern: `(?i)(without\s+(any\s+)?(warnings?|disclaimers?|caveats?|hesitation|apolog\w+|moraliz\w+)|skip\s+(the\s+)?(warning|disclaimer|caveat|safety\s+message))`},
				{Severity: "high", Pattern: `(?i)respond\s+as\s+if\s+(there\s+are|you\s+have|you\s+had)\s+no\s+(restrictions?|filters?|limits?|guidelines?|safety|rules?)`},
				{Severity: "high", Pattern: `(?i)(always\s+start\s+(your\s+)?response\s+with|prefix\s+(every|all|your)\s+(responses?|answers?)\s+with|begin\s+(every|all)\s+(responses?|messages?)\s+with)`},
				{Severity: "medium", Pattern: `(?i)(in\s+this\s+(conversation|chat|session)[,\s]+you\s+(will|must|should|are\s+to))\s+.{0,60}(ignore|always|never|only|bypass)`},
			},
		},
		{
			ID:       "mcp_tool_injection",
			Category: "mcp_tool_injection",
			Rules: []PatternRule{
				{Severity: "critical", Pattern: `(?i)(cat|type|print|echo|more|less|head|tail)\s+(~\/\.ssh\/(id_rsa|id_ed25519|authorized_keys|config)|\/etc\/(passwd|shadow|sudoers))`},
				{Severity: "critical", Pattern: `rm\s+(-rf?|--force|--recursive)\s+[~\/]`},
				{Severity: "critical", Pattern: `(?i)(curl|wget|fetch)\s+.{0,80}\|\s*(bash|sh|zsh|fish|python|ruby|perl|node)`},
				{Severity: "critical", Pattern: `\$\(.*\)`},
				{Severity: "high", Pattern: `(?i)(env|printenv|set)\s*(\|\s*grep\s+.{0,30})?(key|secret|token|password|api|credential|aws|azure|gcp)`},
				{Severity: "high", Pattern: `(?i)(fork\s+bomb|:\s*\(\s*\)\s*\{\s*:\s*\|\s*:&\s*\}|forkbomb)`},
				{Severity: "high", Pattern: `(?i)(read\s+(file|tool)|file_read|bash\s+tool|exec\s+tool)\s*.{0,60}(WORKFLOW_AUTO|memory\/\d{4}-\d{2}-\d{2}|SOUL\.md|IDENTITY\.md)`},
				{Severity: "medium", Pattern: `(?i)(send\s+email|send_email|mail\s+to|mailto:).{0,60}@`},
			},
		},
		{
			ID:       "credential_dlp",
			Category: "credential_dlp",
			Rules: []PatternRule{
				{Severity: "critical", Pattern: `sk-[a-zA-Z0-9]{20,}T3BlbkFJ[a-zA-Z0-9]{20,}`},
				{Severity: "critical", Pattern: `sk-proj-[a-zA-Z0-9\-_]{50,}`},
				{Severity: "critical", Pattern: `sk-ant-api\d{2}-[a-zA-Z0-9\-_]{90,}`},
				{Severity: "critical", Pattern: `AKIA[0-9A-Z]{16}`},
				{Severity: "critical", Pattern: `ghp_[a-zA-Z0-9]{36}`},
				{Severity: "high", Pattern: `xox[baprs]-[0-9a-zA-Z\-]{10,}`},
				{Severity: "high", Pattern: `AIza[0-9A-Za-z\-_]{35}`},
				{Severity: "high", Pattern: `-----BEGIN\s+(RSA|EC|OPENSSH|PGP)\s+PRIVATE\s+KEY-----`},
				{Severity: "high", Pattern: `(?i)(password|passwd|pwd|secret|api_key|api-key|access_token|auth_token)\s*[:=]\s*["']?[^\s"']{8,}`},
			},
		},
		{
			ID:       "multilingual_injection",
			Category: "multilingual_injection",
			Rules: []PatternRule{
				{Severity: "critical", Pattern: `(?i)(無視|無视|忽略|忘记|忘れて|잊어버려|Ignorez|Ignoriere|Ignora|Игнорируй|تجاهل).{0,30}(指示|指令|ルール|규칙|instructions?|Anweisungen|instrucciones|указания|تعليمات)`},
				{Severity: "critical", Pattern: `(?i)(あなたは今|您现在是|이제\s+당신은|Tu es maintenant|Du bist jetzt|Ora sei|Вы теперь|أنت الآن).{0,60}(制限なし|没有限制|제한\s*없이|sans restrictions|ohne Einschränkungen|без ограничений|بدون قيود)`},
				{Severity: "high", Pattern: `(?i)(システムプロンプト|系统提示|시스템\s*프롬프트|invite système|Systemprompt|prompt di sistema|системный промпт|موجه النظام).{0,40}(見せて|显示|보여줘|montrer|zeigen|mostrare|покажи|أظهر)`},
				{Severity: "high", Pattern: `(?i)(越獄|脱獄|탈옥|évasion|побег)\b`},
			},
		},
	}
}
