package config

import (
	"fmt"

	"arkloop/services/shared/creditpolicy"
)

func RegisterTrackB(r *Registry) error {
	if r == nil {
		return fmt.Errorf("registry must not be nil")
	}

	entries := []Entry{
		{
			Key:         "credit.deduction_policy",
			Type:        TypeString,
			Default:     creditpolicy.DefaultPolicyJSON,
			Description: "积分扣减策略（JSON）",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "credit.initial_grant",
			Type:        TypeInt,
			Default:     "1000",
			Description: "新账户初始积分发放数量",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "credit.invite_reward",
			Type:        TypeInt,
			Default:     "500",
			Description: "邀请者奖励积分数量",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "credit.invitee_reward",
			Type:        TypeInt,
			Default:     "200",
			Description: "被邀请者奖励积分数量",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "credit.per_usd",
			Type:        TypeInt,
			Default:     "1000",
			Description: "积分汇率：每 1 USD 对应积分数",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},

		{
			Key:         "feature.byok_enabled",
			Type:        TypeBool,
			Default:     "true",
			Description: "是否允许使用用户级凭证（BYOK）",
			Sensitive:   false,
			Scope:       ScopeBoth,
		},
		{
			Key:         "feature.mcp_remote_enabled",
			Type:        TypeBool,
			Default:     "false",
			Description: "是否允许远程 MCP",
			Sensitive:   false,
			Scope:       ScopeBoth,
		},

		{
			Key:         "invite.default_max_uses",
			Type:        TypeInt,
			Default:     "0",
			Description: "邀请码默认可用次数，0 表示不限",
			Sensitive:   false,
			Scope:       ScopeBoth,
		},
		{
			Key:         "invite.max_codes_per_user",
			Type:        TypeInt,
			Default:     "1",
			Description: "单用户可创建的邀请码数量上限",
			Sensitive:   false,
			Scope:       ScopeBoth,
		},

		{
			Key:         "limit.agent_reasoning_iterations",
			Type:        TypeInt,
			Default:     "0",
			Description: "Agent Loop 主推理回合上限，0 表示不限",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "limit.tool_continuation_budget",
			Type:        TypeInt,
			Default:     "32",
			Description: "长工具 continuation 总预算上限",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "limit.concurrent_runs",
			Type:        TypeInt,
			Default:     "0",
			Description: "并发 run 上限，0 表示不限",
			Sensitive:   false,
			Scope:       ScopeBoth,
		},
		{
			Key:         "limit.max_input_content_bytes",
			Type:        TypeInt,
			Default:     "32768",
			Description: "Run input 提交内容最大字节数",
			Sensitive:   false,
			Scope:       ScopeBoth,
		},
		{
			Key:         "limit.max_parallel_tasks",
			Type:        TypeInt,
			Default:     "32",
			Description: "Lua 并行任务/并行工具调用上限",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "limit.run_wall_clock_timeout_ms",
			Type:        TypeInt,
			Default:     "900000",
			Description: "单个 run 的 wall clock 硬截止时间（毫秒）",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "limit.paused_input_timeout_ms",
			Type:        TypeInt,
			Default:     "300000",
			Description: "run 进入等待用户输入后的超时时间（毫秒）",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "limit.idle_heartbeat_interval_ms",
			Type:        TypeInt,
			Default:     "15000",
			Description: "长等待期间发出活跃事件的心跳间隔（毫秒）",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "limit.team_members",
			Type:        TypeInt,
			Default:     "0",
			Description: "Team 成员数量上限，0 表示不限",
			Sensitive:   false,
			Scope:       ScopeBoth,
		},
		{
			Key:         "limit.thread_message_history",
			Type:        TypeInt,
			Default:     "200",
			Description: "线程历史消息加载上限（条）",
			Sensitive:   false,
			Scope:       ScopeBoth,
		},
		{
			Key:         "context.compact.enabled",
			Type:        TypeBool,
			Default:     "true",
			Description: "启用线程上下文预算裁切（在 Routing 之后）",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "context.compact.max_messages",
			Type:        TypeInt,
			Default:     "0",
			Description: "compact 尾部消息条数上限，0 表示仅按 token/字节预算",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "context.compact.max_user_message_tokens",
			Type:        TypeInt,
			Default:     "0",
			Description: "保留 user 的 tiktoken 累计上限（role+正文），0 表示不限制",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "context.compact.max_total_text_tokens",
			Type:        TypeInt,
			Default:     "0",
			Description: "全消息 tiktoken 累计上限（role+正文），0 表示不限制",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "context.compact.max_user_text_bytes",
			Type:        TypeInt,
			Default:     "0",
			Description: "保留 user 文本字节上限，0 表示不限制",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "context.compact.max_total_text_bytes",
			Type:        TypeInt,
			Default:     "0",
			Description: "全消息文本字节上限，0 表示不限制",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "context.compact.persist_enabled",
			Type:        TypeBool,
			Default:     "true",
			Description: "超阈值时将较早消息摘要并标记 compacted（需迁移 00134）",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "context.compact.persist_trigger_approx_tokens",
			Type:        TypeInt,
			Default:     "120000",
			Description: "触发持久化摘要的 token 阈值（tiktoken）；PersistTriggerContextPct>0 时忽略此项",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "context.compact.persist_trigger_context_pct",
			Type:        TypeInt,
			Default:     "80",
			Description: "按路由 available_catalog.context_length（否则 fallback）的百分比触发 persist，0 表示只用 persist_trigger_approx_tokens",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "context.compact.fallback_context_window_tokens",
			Type:        TypeInt,
			Default:     "128000",
			Description: "路由 advanced_json 未解析出上下文窗口时用于百分比换算的窗口上限",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "context.compact.persist_keep_last_messages",
			Type:        TypeInt,
			Default:     "40",
			Description: "持久化摘要时保留的尾部消息条数（兜底上限）",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "context.compact.persist_keep_tail_pct",
			Type:        TypeInt,
			Default:     "25",
			Description: "persist 时保留 context window 的百分比作为尾部 token 预算（1-100）；0 = 仅按条数",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "context.compact.microcompact_keep_recent_tools",
			Type:        TypeInt,
			Default:     "8",
			Description: "microcompact 保留最近 N 个 tool result 原文，0 = 不做 microcompact",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},

		{
			Key:         "llm.max_response_bytes",
			Type:        TypeInt,
			Default:     "16384",
			Description: "LLM Provider HTTP 响应读取上限（字节）",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "skills.registry.provider",
			Type:        TypeString,
			Default:     "clawhub",
			Description: "官方技能 Registry Provider",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "skills.registry.base_url",
			Type:        TypeString,
			Default:     "https://clawhub.ai",
			Description: "官方技能 Registry 页面基础地址",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "skills.registry.api_base_url",
			Type:        TypeString,
			Default:     "",
			Description: "官方技能 Registry API 基础地址，留空则沿用 Base URL",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "skills.registry.api_key",
			Type:        TypeString,
			Default:     "",
			Description: "官方技能 Registry API Key",
			Sensitive:   true,
			Scope:       ScopePlatform,
		},
		{
			Key:         "skills.market.skillsmp_api_key",
			Type:        TypeString,
			Default:     "",
			Description: "SkillsMP 官方市场 API Key",
			Sensitive:   true,
			Scope:       ScopePlatform,
		},
		{
			Key:         "skills.market.skillsmp_base_url",
			Type:        TypeString,
			Default:     "https://skillsmp.com",
			Description: "SkillsMP 官方市场基础地址",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},

		{
			Key:         "quota.runs_per_month",
			Type:        TypeInt,
			Default:     "0",
			Description: "每月 run 数量配额，0 表示不限",
			Sensitive:   false,
			Scope:       ScopeBoth,
		},
		{
			Key:         "quota.tokens_per_month",
			Type:        TypeInt,
			Default:     "0",
			Description: "每月 token 配额，0 表示不限",
			Sensitive:   false,
			Scope:       ScopeBoth,
		},

		{
			Key:         "browser.enabled",
			Type:        TypeBool,
			Default:     "false",
			Description: "是否在 Worker 中注册 browser 自动化工具",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_BROWSER_ENABLED"},
		},
		{
			Key:         "sandbox.base_url",
			Type:        TypeString,
			Default:     "",
			Description: "Sandbox Service 地址，Worker 通过此 URL 调用 Sandbox；为空则不注册 sandbox 工具",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_SANDBOX_BASE_URL"},
		},
		{
			Key:         "sandbox.provider",
			Type:        TypeString,
			Default:     "firecracker",
			Description: "Sandbox 后端类型：firecracker / docker",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "sandbox.allow_egress",
			Type:        TypeBool,
			Default:     "true",
			Description: "Sandbox backend 是否允许访问外网",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_SANDBOX_ALLOW_EGRESS"},
		},
		{
			Key:         "sandbox.docker_image",
			Type:        TypeString,
			Default:     "arkloop/sandbox-agent:latest",
			Description: "Docker 后端使用的 sandbox-agent 镜像",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_SANDBOX_DOCKER_IMAGE"},
		},
		{
			Key:         "sandbox.browser_docker_image",
			Type:        TypeString,
			Default:     "arkloop/sandbox-browser:dev",
			Description: "Docker browser tier 使用的 sandbox-agent 镜像",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_SANDBOX_BROWSER_DOCKER_IMAGE"},
		},
		{
			Key:         "sandbox.max_sessions",
			Type:        TypeInt,
			Default:     "50",
			Description: "Sandbox 最大并发 session 数",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "sandbox.agent_port",
			Type:        TypeInt,
			Default:     "8080",
			Description: "Sandbox Agent 监听端口",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "sandbox.boot_timeout_s",
			Type:        TypeInt,
			Default:     "30",
			Description: "VM/容器启动超时（秒）",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "sandbox.warm_lite",
			Type:        TypeInt,
			Default:     "3",
			Description: "lite tier 预热实例数",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "sandbox.warm_pro",
			Type:        TypeInt,
			Default:     "2",
			Description: "pro tier 预热实例数",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_SANDBOX_WARM_PRO"},
		},
		{
			Key:         "sandbox.warm_browser",
			Type:        TypeInt,
			Default:     "1",
			Description: "browser tier 预热实例数",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_SANDBOX_WARM_BROWSER"},
		},
		{
			Key:         "sandbox.refill_interval_s",
			Type:        TypeInt,
			Default:     "5",
			Description: "预热补充检查间隔（秒）",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "sandbox.refill_concurrency",
			Type:        TypeInt,
			Default:     "2",
			Description: "预热补充最大并发数",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},

		{
			Key:         "sandbox.credit_base_fee",
			Type:        TypeInt,
			Default:     "1",
			Description: "每次 sandbox 调用的固定积分扣减，覆盖冷启动/调度开销",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},
		{
			Key:         "sandbox.credit_rate_per_second",
			Type:        TypeNumber,
			Default:     "0.5",
			Description: "sandbox 每秒执行时长对应的积分费率",
			Sensitive:   false,
			Scope:       ScopePlatform,
		},

		{
			Key:         "sandbox.idle_timeout_lite_s",
			Type:        TypeInt,
			Default:     "180",
			Description: "Sandbox lite tier 空闲超时（秒）",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_SANDBOX_IDLE_TIMEOUT_LITE_S", "ARKLOOP_SANDBOX_IDLE_TIMEOUT_LITE"},
		},
		{
			Key:         "sandbox.idle_timeout_pro_s",
			Type:        TypeInt,
			Default:     "300",
			Description: "Sandbox pro tier 空闲超时（秒）",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_SANDBOX_IDLE_TIMEOUT_PRO_S", "ARKLOOP_SANDBOX_IDLE_TIMEOUT_PRO"},
		},
		{
			Key:         "sandbox.idle_timeout_browser_s",
			Type:        TypeInt,
			Default:     "120",
			Description: "Sandbox browser tier 空闲超时（秒）",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_SANDBOX_IDLE_TIMEOUT_BROWSER_S", "ARKLOOP_SANDBOX_IDLE_TIMEOUT_BROWSER"},
		},
		{
			Key:         "sandbox.max_lifetime_s",
			Type:        TypeInt,
			Default:     "1800",
			Description: "Sandbox session 最大存活时间（秒）",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_SANDBOX_MAX_LIFETIME_S", "ARKLOOP_SANDBOX_MAX_LIFETIME"},
		},
		{
			Key:         "sandbox.max_lifetime_browser_s",
			Type:        TypeInt,
			Default:     "600",
			Description: "Sandbox browser tier 最大存活时间（秒）",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_SANDBOX_MAX_LIFETIME_BROWSER_S", "ARKLOOP_SANDBOX_MAX_LIFETIME_BROWSER"},
		},
		{
			Key:         "sandbox.restore_ttl_days",
			Type:        TypeInt,
			Default:     "7",
			Description: "session restore state 保留天数",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_SANDBOX_RESTORE_TTL_DAYS", "ARKLOOP_SANDBOX_SESSION_STATE_TTL_DAYS"},
		},
		{
			Key:         "sandbox.flush_debounce_ms",
			Type:        TypeInt,
			Default:     "2000",
			Description: "flush debounce 延迟（毫秒）",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_SANDBOX_FLUSH_DEBOUNCE_MS"},
		},
		{
			Key:         "sandbox.flush_max_dirty_age_ms",
			Type:        TypeInt,
			Default:     "15000",
			Description: "触发强制 flush 的最大 dirty 年龄（毫秒）",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_SANDBOX_FLUSH_MAX_DIRTY_AGE_MS"},
		},
		{
			Key:         "sandbox.flush_force_bytes_threshold",
			Type:        TypeInt,
			Default:     "16777216",
			Description: "触发强制 flush 的累计字节阈值",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_SANDBOX_FLUSH_FORCE_BYTES_THRESHOLD"},
		},
		{
			Key:         "sandbox.flush_force_count_threshold",
			Type:        TypeInt,
			Default:     "512",
			Description: "触发强制 flush 的 dirty 数量阈值",
			Sensitive:   false,
			Scope:       ScopePlatform,
			EnvKeys:     []string{"ARKLOOP_SANDBOX_FLUSH_FORCE_COUNT_THRESHOLD"},
		},
	}

	for _, e := range entries {
		if err := r.Register(e); err != nil {
			return err
		}
	}
	return nil
}
